version: "3"

services:
  postgres:
    image: postgres:10-alpine3.15
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - '127.0.0.1:${POSTGRES_PORT}:${POSTGRES_PORT}'

  pgadmin:
    depends_on:
      - postgres
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD
    ports:
      - '${PGADMIN_PORT}:80'

  backend:
    build:
      context: .
      dockerfile: ./docker/backend/DockerFile
    volumes:
      - './backend:/app'
    ports:
      - '${BACKEND_PORT}:80'
    command: sh -c "
      npm install &&
      npm run dev"

